name: "Duplicates Checker"
description: "Checks all files in a given scope for duplicate text that can be harmul when deployed"
author: "Heap"
inputs:
  check_name:
    description: "A name for this check"
    required: false
  directory_scope:
    description: "Checks for duplicates will be evaluated in the scope of this directory"
    required: true
  check_file_extension:
    description: "Checks for duplicates will be done only for files with this extension" 
    required: true
  content_regex:
    description: "The regular expression to use in checking for content"
    required: true
  max_files_to_process:
    description: "This threshold limits the number of files to scan. It's a safeguard against locking up your build by scanning too many files. Default is 500"
    required: false
    default: "500"
  max_file_size_bytes:
    description: "This threshold limits the size of files to scan, to prevent memory overload. Default is 200Kb"
    required: false
    default: "200000"
  excluded_extensions:
    description: "A comma delimited list of extensions to skip (extensions can include the dot prefix or not). This configuration allows skipping over files with certain extensions"
    required: false
    default: ""
  ignore_files:
    description: "A comma delimited list of filenames to skip. This configuration allows skipping certain file names. Useful if you use the same settings in multiple environment configuration files."
    required: false
    default: ""
  ignore_paths_containing:
    description: "A comma delimited list of paths to skip. This configuration allows skipping certain paths. Useful if you have generated paths that have copies of files you do not want to check for duplicates."
    required: true
  error_message:
    description: "The message to output if duplicates are found"
    required: true
outputs:
  has_duplicates:
    description: "True or false depending on if the check found duplicates"
  result_title:
    description: "Title caption of result summary"
  result:
    description: "The output after evaluating all checks"
  result_escaped:
    description: "The output after evaluating all checks in escaped json format"
runs:
  using: "docker"
  image: "Dockerfile"